Level Order Traversal of Binary Tree
AlgoGenesis/C pull request #1554
Opened 2024-11-01 12:13 UTC by Arghya-Chakraborty0812

Fixes#1466
Level oder Traversal of Binary tree.
Algorithm:

1. **Build Tree**: Starting with the root node, ask the user to input values for each node.
    - For each node, take user input to determine its left and right children.
    - If the input is `-1`, that child is considered `NULL` (no node).
2. **Level Order Traversal**:
    - Initialize a queue to hold nodes at each level.
    - For each node in the queue:
      - Print the node’s value.
      - Add its left and right children to the queue (if they exist).
    - Each level is printed on a new line.
Please review and merge my PR with appropriate tags.
Thanks

2024-11-02 10:35 UTC, pankaj-bind requested changes
![{86470825-F78E-4037-BABC-5951DB2F167A}](https://github.com/user-attachments/assets/39838206-bac2-473d-9a4d-bfab8f4f4940)
delete middle program file

2024-11-02 11:58 UTC, Arghya-Chakraborty0812 commented
@pankaj-bind Changes done

2024-11-04 07:11 UTC, pankaj-bind approved these changes

2024-11-04 07:12 UTC, merged

2024-11-04 07:13 UTC, pankaj-bind commented
#1466