Stack implementation using array
AlgoGenesis/C pull request #1733
Opened 2024-11-07 17:38 UTC by Srija-11

**### Related Issue**
Fixes: #1700 

### **Description**
Stack implementation using array

### **Checklist:**
 

- [ ] I have made this change from my own.
- [ ]  My code follows the style guidelines of this project.
- [ ]  I have performed a self-review of my own code.
- [ ]  My changes generate no new warnings.
- [ ]  I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

Please add GSSOC EXTD and level labels to the PR

2024-11-07 17:42 UTC, Srija-11 commented
@pankaj-bind please merge it fast as the deadline is 10th november

2024-11-08 07:03 UTC, pankaj-bind requested changes
move this to StackQueue folder

2024-11-08 13:54 UTC, Srija-11 commented
> move this to StackQueue folder

done

2024-11-08 18:32 UTC, pankaj-bind approved these changes

2024-11-08 18:32 UTC, merged