Create Bézout’s Identity (Extended Euclidean Algorithm)
AlgoGenesis/C pull request #1759
Opened 2024-11-08 11:49 UTC by ananyashinde2434

Bézout’s Identity is a fundamental theorem in number theory that states: for any two integers  𝑎
a and 
𝑏
b with a greatest common divisor 
𝑑
d, there exist two integers 
𝑥
x and 
𝑦
y such that:

𝑎
𝑥
+
𝑏
𝑦
=
𝑑
ax+by=d
The Extended Euclidean Algorithm is an extension of the Euclidean algorithm that not only finds the GCD of two integers  𝑎
a and 
𝑏
b but also finds the coefficients 
𝑥
x and 
𝑦
y that satisfy Bézout's Identity. This algorithm has practical applications in:

Solving linear Diophantine equations.
Computing modular inverses (important in cryptography). Finding integer solutions in various number theory problems.

2024-11-08 18:47 UTC, pankaj-bind requested changes
Readme.md file missing

2024-11-08 19:12 UTC, ananyashinde2434 commented
can u tell me how do i add that ?

2024-11-08 19:24 UTC, pankaj-bind commented
@ananyashinde2434 do you know how to operate git on vs code

2024-11-08 19:27 UTC, pankaj-bind commented
do one thing open this https://github.com/ananyashinde2434/C and press Dot button .  this will convert your github into VS code environment and you will be more comfortable to contribute.

2024-11-08 19:31 UTC, pankaj-bind commented
But before that sync latest changes on you github by this
![Uploading {0AE3C4F7-5850-4F50-B9F7-A73DD4C97224}.png…]()

2024-11-09 05:17 UTC, ananyashinde2434 commented
can u tell me where is the dot button u r talking about ?

2024-11-09 19:00 UTC, pankaj-bind commented
dot button on keybord

2024-11-09 19:11 UTC, merged